/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projekqueue;

/**
 *
 * @author Robbi Nanda
 */
import java.util.*;

public class Game_Tembak extends javax.swing.JFrame {
    static String [] Warna={"/projekqueue/biru.png","/projekqueue/merah.png",
                             "/projekqueue/kuning.png"};
    static String [] Slot= new String[4];
    static int tail = 0;
    
    
    public void warnaslot1(){
        if (Slot[0]==null){
            slot1.setIcon(null);
            JPTanda.setBackground(new java.awt.Color(0,0,0));
        }
        else{
        slot1.setIcon(new javax.swing.ImageIcon(getClass().getResource(Slot[0])));
        JPTanda.setBackground(new java.awt.Color(255, 255, 255));
        JPTanda.setBorder(new javax.swing.border.MatteBorder(null));
                }
    }
    public void warnaslot2(){
        if (Slot[1]==null){
            slot2.setIcon(null);
        }
        else{
        slot2.setIcon(new javax.swing.ImageIcon(getClass().getResource(Slot[1])));
                }
    }
    public void warnaslot3(){
        if (Slot[2]==null){
        slot3.setIcon(null);
        }
        else {
           slot3.setIcon(new javax.swing.ImageIcon(getClass().getResource(Slot[2])));
        }
    }
    public void warnaslot4(){
        if (Slot[3]==null){
         slot4.setIcon(null);
        }
        else{
        slot4.setIcon(new javax.swing.ImageIcon(getClass().getResource(Slot[3])));
        }
    }
    public void tembak(){
        
            if(tail==4){
                Info.setText(null);
            int i=1;
            while(i<tail)
            {
                Slot[i-1]=Slot[i];
                i++;
               
            }
            Slot[i-1]=null;
            tail--;
            warnaslot4();
            warnaslot3();
            warnaslot2();
            warnaslot1();
            }
            else if(tail==3){
                Info.setText(null);
            int i=1;
            while(i<tail)
            {
                Slot[i-1]=Slot[i];
                i++;
               
            }
            Slot[i-1]=null;
            tail--;
            warnaslot4();
            warnaslot3();
            warnaslot2();
            warnaslot1();
            }
            else if(tail==2){
                Info.setText(null);
            int i=1;
            while(i<tail)
            {
                Slot[i-1]=Slot[i];
                i++;
               
            }
            Slot[i-1]=null;
            tail--;
            warnaslot4();
            warnaslot3();
            warnaslot2();
            warnaslot1();
            }
            else if(tail==1){
                Info.setText(null);
            int i=1;
            while(i<tail)
            {
                Slot[i-1]=Slot[i];
                i++;
               
            }
            Slot[i-1]=null;
            tail--;
            warnaslot4();
            warnaslot3();
            warnaslot2();
            warnaslot1();
            }
            else if(tail<=0){
            Info.setText("Peluru Kosong, Reload!!!");
            }
        
            
            
        
    }
    
    public void reload_peluru()
    {
        if(tail>=4)
            Info.setText("Peluru Penuh!");
        else if (tail==3)
        {
            Info.setText(null);
            Slot[tail]=Warna[tail-tail];
            slot4.setIcon(new javax.swing.ImageIcon(getClass().getResource(Slot[tail])));
            tail++;
        }
        else if(tail==2){
            Info.setText(null);
            Slot[tail]=Warna[tail];
            slot3.setIcon(new javax.swing.ImageIcon(getClass().getResource(Slot[tail])));
            tail++;
        }
        else if(tail==1){
            Info.setText(null);
            Slot[tail]=Warna[tail];
            slot2.setIcon(new javax.swing.ImageIcon(getClass().getResource(Slot[tail])));
            tail++;
        }
        else if(tail==0){
            Info.setText(null); 
            Slot[tail]=Warna[tail];
            slot1.setIcon(new javax.swing.ImageIcon(getClass().getResource(Slot[tail])));
            tail++;
        }
    }

    /**
     * Creates new form Reload_Peluru
     */
    public Game_Tembak() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Tembak = new javax.swing.JButton();
        Reload = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        slot1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        slot2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        slot3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        slot4 = new javax.swing.JLabel();
        JPTanda = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Info = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tembak.setText("Tembak");
        Tembak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TembakActionPerformed(evt);
            }
        });
        jPanel1.add(Tembak, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        Reload.setText("Reload");
        Reload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReloadActionPerformed(evt);
            }
        });
        jPanel1.add(Reload, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slot1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slot1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 50, 50));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slot2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slot2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 50, 50));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slot3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slot3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 50, 50));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slot4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slot4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 50, 50));

        JPTanda.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout JPTandaLayout = new javax.swing.GroupLayout(JPTanda);
        JPTanda.setLayout(JPTandaLayout);
        JPTandaLayout.setHorizontalGroup(
            JPTandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        JPTandaLayout.setVerticalGroup(
            JPTandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(JPTanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 10, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projekqueue/guns.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 127, 127));

        Info.setBackground(new java.awt.Color(255, 255, 255));
        Info.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        Info.setForeground(new java.awt.Color(255, 255, 255));
        Info.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 180, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TembakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TembakActionPerformed
        // TODO add your handling code here:
        tembak();
        
    }//GEN-LAST:event_TembakActionPerformed

    private void ReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReloadActionPerformed
        // TODO add your handling code here:
        reload_peluru();
        JPTanda.setBackground(new java.awt.Color(0,0,0));
        
    }//GEN-LAST:event_ReloadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game_Tembak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game_Tembak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game_Tembak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game_Tembak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game_Tembak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Info;
    private javax.swing.JPanel JPTanda;
    private javax.swing.JButton Reload;
    private javax.swing.JButton Tembak;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel slot1;
    private javax.swing.JLabel slot2;
    private javax.swing.JLabel slot3;
    private javax.swing.JLabel slot4;
    // End of variables declaration//GEN-END:variables
}
